In [3]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.options.display.float_format = '{:.2f}'.format

In [4]:
apple_df = pd.read_csv('applemobilitytrends-2020-06-07.csv')
apple_df

,County,1/13/2020,1/14/2020,1/15/2020,1/16/2020,1/17/2020,1/18/2020,1/19/2020,1/20/2020,1/21/2020,...,6/2/2020,6/3/2020,6/4/2020,6/5/2020,6/6/2020,6/7/2020,6/8/2020,6/9/2020,6/10/2020,6/11/2020
0,Alameda,100,102.85,106.26,107.14,124.52,114.00,85.41,98.52,108.80,...,77.00,80.61,85.44,95.69,87.19,71.43,84.17,87.73,89.76,90.45
1,Amador,100,96.24,106.20,102.14,135.68,156.08,139.18,130.96,100.83,...,126.17,137.54,135.98,166.57,179.25,167.15,149.62,144.81,147.98,149.14
2,Butte,100,104.07,110.58,105.22,120.22,117.22,93.48,113.61,115.22,...,135.54,136.78,147.59,157.51,141.53,117.85,140.13,144.75,194.73,146.94
3,Calaveras,100,93.35,101.68,89.01,121.29,146.71,127.92,131.48,97.07,...,134.25,141.17,146.75,168.09,205.99,167.02,147.23,151.23,155.86,157.01
4,Colusa,100,95.78,105.51,110.63,140.67,138.89,112.32,128.54,98.64,...,129.74,133.96,152.77,175.63,160.37,171.87,144.15,140.88,143.80,168.38
5,Contra Costa,100,104.51,104.75,102.60,121.76,109.43,82.13,95.18,103.59,...,90.50,94.41,99.85,109.54,108.08,88.97,103.77,105.44,105.16,109.01
6,Del Norte,100,98.60,93.52,134.61,126.95,116.94,113.77,118.04,105.45,...,164.80,163.99,163.70,181.15,256.55,203.09,187.41,198.82,184.54,196.76
7,El Dorado,100,90.05,93.60,96.77,142.74,168.38,139.12,153.37,91.28,...,110.03,116.12,124.68,147.42,157.27,135.83,127.97,135.60,138.95,145.31
8,Fresno,100,97.82,104.81,103.41,121.70,110.31,84.16,100.12,103.10,...,117.08,122.39,126.06,141.95,129.49,106.04,125.12,126.17,128.70,133.18
9,Glenn,100,98.34,99.14,105.22,126.73,125.13,99.72,114.84,101.63,...,136.59,133.06,143.50,193.58,168.36,168.91,154.84,148.33,159.48,164.15
10,Humboldt,100,100.33,101.37,103.95,112.14,115.47,102.73,106.96,100.41,...,130.24,135.22,138.37,141.77,138.76,129.35,147.64,140.76,150.38,156.48
11,Imperial,100,101.53,110.68,111.66,161.48,151.48,123.87,122.49,101.40,...,101.51,104.86,121.00,142.01,123.13,114.87,113.69,113.55,112.45,118.10
12,Inyo,100,90.60,96.22,117.18,206.64,142.97,148.05,185.72,89.39,...,96.75,110.75,121.36,153.95,149.42,163.72,119.43,114.28,127.48,150.14
13,Kern,100,101.91,109.34,112.80,145.44,135.78,105.00,120.06,114.06,...,127.61,132.20,138.89,158.15,151.91,131.77,139.97,141.03,141.73,149.73
14,Kings,100,98.79,102.59,105.62,138.32,124.21,101.64,123.18,106.50,...,124.62,132.17,136.98,151.38,151.33,126.79,137.27,136.16,134.34,144.65
15,Lake,100,108.31,112.86,109.27,126.09,116.15,98.07,109.51,120.00,...,134.40,138.96,158.36,166.93,160.16,138.02,150.49,155.47,158.07,159.87
16,Lassen,100,82.54,84.68,99.07,124.66,106.56,94.87,103.35,90.02,...,183.75,203.42,204.21,256.38,251.82,230.79,200.43,235.71,209.91,250.96
17,Los Angeles,100,105.94,112.85,111.09,127.76,121.16,92.43,100.56,109.10,...,71.60,78.93,81.13,90.96,87.55,75.91,83.77,87.70,91.43,92.89
18,Madera,100,95.90,105.28,102.72,123.87,123.97,100.49,109.24,100.18,...,121.93,126.25,128.20,156.54,153.43,130.21,139.95,147.62,137.27,142.20
19,Marin,100,103.89,108.41,110.32,123.46,118.99,94.39,104.44,116.99,...,88.14,94.41,96.44,103.90,108.31,90.44,96.17,102.34,104.43,104.56
20,Mariposa,100,95.06,103.21,85.72,102.14,146.77,157.08,128.21,96.56,...,59.22,66.22,67.21,74.03,83.17,96.05,99.82,131.80,121.18,139.46
21,Mendocino,100,96.36,103.03,107.98,123.24,124.38,111.48,119.56,103.43,...,126.38,124.01,129.90,142.07,139.31,127.02,133.70,138.47,138.03,145.53
22,Merced,100,102.86,100.21,103.94,141.39,127.35,111.55,122.29,103.37,...,119.38,124.92,128.00,151.93,153.48,126.65,136.19,128.85,133.10,137.99
23,Mono,100,100.87,92.44,113.31,210.03,237.19,217.19,185.17,91.71,...,89.54,96.23,118.11,145.13,171.43,159.45,134.35,128.76,135.40,154.03
24,Monterey,100,97.63,102.52,102.66,132.55,147.03,123.46,122.41,105.52,...,113.15,115.99,117.15,132.83,148.09,124.45,122.15,127.49,128.17,132.97
25,Napa,100,102.77,107.67,101.92,132.16,145.51,116.69,107.52,98.79,...,96.42,98.40,102.45,114.31,119.24,105.56,103.85,112.53,113.94,115.14
26,Nevada,100,88.51,92.40,88.41,165.16,157.65,128.58,189.41,91.23,...,117.75,127.41,133.67,148.23,147.24,125.34,131.78,132.92,140.42,148.07
27,Orange,100,106.72,112.16,113.34,135.60,129.15,96.41,106.98,108.17,...,81.50,88.96,90.62,101.67,98.62,82.57,91.99,98.26,101.34,105.57
28,Placer,100,100.43,103.66,102.76,138.64,131.50,97.54,136.31,100.19,...,114.91,118.96,125.19,141.16,140.29,119.29,126.40,128.32,134.14,134.15
29,Riverside,100,102.15,108.61,111.09,138.57,135.93,103.74,109.95,105.64,...,97.06,104.47,108.05,122.96,118.03,100.28,108.02,108.46,110.54,114.92
30,Sacramento,100,102.34,107.35,103.13,123.79,112.78,83.61,97.00,110.24,...,98.25,101.11,105.67,121.86,119.32,94.80,107.16,110.58,109.82,113.05
31,San Benito,100,97.68,98.89,95.21,125.50,123.34,110.65,104.03,100.28,...,119.61,125.52,123.69,143.79,146.43,117.47,124.41,125.72,128.49,132.81
32,San Bernardino,100,101.51,105.65,110.66,140.50,123.23,99.09,111.38,103.32,...,96.37,104.76,110.30,133.96,123.45,108.10,111.53,114.23,115.67,120.38
33,San Diego,100,108.32,112.27,114.17,130.18,121.53,95.17,103.74,111.82,...,87.45,91.00,93.48,103.47,104.90,88.09,95.23,98.92,99.98,103.46
34,San Francisco,100,104.71,104.32,101.92,121.95,135.84,100.80,92.87,96.43,...,55.47,68.34,61.48,68.33,68.95,57.89,61.36,65.68,66.15,70.00
35,San Joaquin,100,99.05,102.18,99.65,131.15,114.62,83.98,100.91,100.17,...,119.01,120.02,123.43,146.78,133.91,108.21,125.85,127.13,126.36,128.03
36,San Luis Obispo,100,102.70,107.74,116.38,162.73,179.35,151.33,143.58,107.82,...,120.12,129.24,138.46,160.84,187.38,165.97,141.67,143.71,148.79,166.95
37,San Mateo,100,102.91,106.30,110.82,124.59,103.31,81.40,90.78,105.30,...,69.74,74.31,74.10,80.90,78.47,66.84,72.49,76.34,78.46,79.65
38,Santa Barbara,100,104.29,113.00,112.88,148.94,154.49,129.98,128.52,108.23,...,102.45,106.98,110.22,125.74,134.88,123.12,113.88,118.52,121.13,129.96
39,Santa Clara,100,104.40,106.11,105.51,120.76,106.01,88.15,92.48,104.74,...,70.60,73.98,78.19,88.68,82.34,68.69,78.45,80.82,83.15,84.10
40,Santa Cruz,100,100.63,98.02,99.13,120.20,117.63,97.53,102.67,97.25,...,88.21,106.44,101.11,107.68,126.85,112.30,101.17,107.70,123.09,115.47
41,Shasta,100,101.56,102.74,113.85,118.65,111.06,88.37,101.63,94.73,...,138.42,149.45,154.43,173.06,163.42,141.81,160.64,158.26,158.01,171.91
42,Siskiyou,100,93.96,86.31,138.50,138.77,149.09,131.65,135.70,96.87,...,199.20,195.81,228.35,241.38,276.72,263.94,235.39,228.74,242.41,267.54
43,Solano,100,101.53,103.65,103.74,135.20,134.15,96.41,111.37,99.42,...,105.33,103.85,109.55,126.50,129.85,106.95,115.02,113.19,116.79,120.99
44,Sonoma,100,102.05,103.33,100.60,119.46,115.25,91.11,99.86,99.22,...,97.42,98.55,104.77,114.58,111.85,92.47,104.56,107.54,110.06,111.42
45,Stanislaus,100,97.91,100.55,100.57,116.69,109.54,81.90,94.70,99.31,...,114.92,117.38,119.37,136.93,131.07,107.15,123.48,124.48,124.97,131.53
46,Sutter,100,101.28,101.99,103.27,119.73,114.99,86.53,103.56,102.79,...,136.88,135.04,136.66,154.55,150.24,115.89,135.35,140.16,143.27,141.28
47,Tehama,100,106.85,107.43,121.22,135.80,134.83,102.97,109.34,111.21,...,149.23,141.19,168.63,205.05,177.75,170.61,159.96,166.29,167.51,185.97
48,Tulare,100,98.09,101.97,103.86,122.16,117.79,91.28,103.65,101.92,...,130.80,134.12,138.41,154.01,143.61,120.70,140.12,138.21,139.64,146.19
49,Tuolumne,100,101.97,107.85,95.76,128.54,186.54,148.31,145.05,103.56,...,138.29,147.14,163.31,181.07,198.05,175.44,167.85,169.33,178.43,180.15
50,Ventura,100,104.80,112.84,112.53,132.88,128.37,98.04,110.53,108.63,...,102.14,108.00,110.24,124.47,126.19,111.80,110.05,116.42,121.83,122.30
51,Yolo,100,100.24,107.65,105.90,148.56,120.23,87.43,110.68,103.13,...,89.83,93.78,98.22,112.46,103.81,89.63,97.79,101.22,106.02,110.28
52,Yuba,100,102.98,103.10,114.08,118.83,121.49,93.29,101.86,103.01,...,133.18,142.45,153.59,175.49,183.92,157.73,151.66,150.58,152.14,148.45

In [5]:
apple = pd.melt(apple_df, 
            id_vars='County', 
            value_vars=list(apple_df.columns[1:155]), # list of days of the week
            var_name='Date', 
            value_name='Index')
apple

         County       Date  Index
0       Alameda  1/13/2020 100.00
1        Amador  1/13/2020 100.00
2         Butte  1/13/2020 100.00
3     Calaveras  1/13/2020 100.00
4        Colusa  1/13/2020 100.00
...         ...        ...    ...
7998     Tulare  6/11/2020 146.19
7999   Tuolumne  6/11/2020 180.15
8000    Ventura  6/11/2020 122.30
8001       Yolo  6/11/2020 110.28
8002       Yuba  6/11/2020 148.45

[8003 rows x 3 columns]

In [6]:
apple.to_csv('apple.csv')

In [18]:
demos_df = pd.read_csv('county_demos.csv')
demos_df

,Category,California,Alameda,Alpine,Amador,Butte,Calaveras,Colusa,Contra Costa,Del Norte,...,Sonoma,Stanislaus,Sutter,Tehama,Trinity,Tulare,Tuolumne,Ventura,Yolo,Yuba
0,Population,"39,512,223","1,671,329","1,129","39,752","219,186","45,905","21,547","1,153,526","27,812",...,"494,336","550,660","96,971","65,084","12,285","466,195","54,478","846,006","220,500","78,668"
1,<18,22.70%,20.50%,17.50%,15.00%,20.00%,16.90%,27.30%,22.60%,21.00%,...,19.60%,27.10%,25.90%,24.00%,17.10%,30.70%,16.80%,22.90%,21.00%,27.60%
2,18-64,63.00%,65.70%,57.10%,58.00%,61.40%,55.60%,58.10%,61.60%,61.00%,...,60.70%,59.70%,58.70%,56.60%,55.60%,57.90%,57.00%,61.50%,66.50%,59.60%
3,>=65,14.30%,13.80%,25.40%,27.00%,18.60%,27.50%,14.60%,15.80%,18.00%,...,19.70%,13.20%,15.40%,19.40%,27.30%,11.40%,26.20%,15.60%,12.50%,12.80%
4,Female,50.30%,50.80%,46.60%,45.60%,50.60%,50.20%,48.90%,51.10%,45.40%,...,51.20%,50.50%,50.20%,50.30%,48.60%,50.00%,48.10%,50.50%,51.60%,49.40%
5,Male,49.70%,49.20%,53.40%,54.40%,49.40%,49.80%,51.10%,48.90%,54.60%,...,48.80%,49.50%,49.80%,49.70%,51.40%,50.00%,51.90%,49.50%,48.40%,50.60%
6,Others,2.10%,3.50%,22.40%,3.80%,5.00%,4.20%,2.50%,3.50%,11.00%,...,3.00%,2.30%,3.50%,4.30%,8.60%,0.50%,4.10%,1.70%,3.80%,5.10%
7,Black,6.50%,11.20%,0.10%,2.70%,1.80%,1.00%,1.20%,9.50%,3.50%,...,2.10%,3.50%,2.70%,1.00%,0.70%,2.20%,2.00%,2.40%,3.00%,4.40%
8,Asian,15.30%,31.80%,2.00%,1.70%,4.90%,1.70%,1.70%,18.00%,3.10%,...,4.60%,6.10%,17.00%,1.40%,1.40%,4.00%,1.40%,7.90%,15.00%,7.50%
9,Hispanic,39.30%,22.40%,11.40%,14.40%,16.70%,12.40%,60.30%,25.80%,20.00%,...,27.20%,47.00%,31.50%,25.70%,7.50%,65.20%,12.70%,43.00%,31.90%,28.70%
10,White,36.80%,31.10%,64.10%,77.40%,71.60%,80.70%,34.30%,43.20%,62.40%,...,63.10%,41.10%,45.30%,67.60%,81.80%,28.10%,79.80%,45.00%,46.30%,54.30%

In [19]:
demos = pd.melt(demos_df, 
            id_vars='Category', 
            value_vars=list(demos_df.columns[1:59]),
            var_name='County', 
            value_name='Value')
demos

       Category      County       Value
0    Population  California  39,512,223
1           <18  California      22.70%
2         18-64  California      63.00%
3          >=65  California      14.30%
4        Female  California      50.30%
..          ...         ...         ...
633      Others        Yuba       5.10%
634       Black        Yuba       4.40%
635       Asian        Yuba       7.50%
636    Hispanic        Yuba      28.70%
637       White        Yuba      54.30%

[638 rows x 3 columns]

In [11]:
states_df = pd.read_csv('us-states.csv')
states_df

           date    state  fips  cases  deaths
0     3/13/2020  Alabama     1      6       0
1     3/14/2020  Alabama     1     12       0
2     3/15/2020  Alabama     1     23       0
3     3/16/2020  Alabama     1     29       0
4     3/17/2020  Alabama     1     39       0
...         ...      ...   ...    ...     ...
5454   6/5/2020  Wyoming    56    933      17
5455   6/6/2020  Wyoming    56    939      17
5456   6/7/2020  Wyoming    56    947      17
5457   6/8/2020  Wyoming    56    960      17
5458   6/9/2020  Wyoming    56    970      17

[5459 rows x 5 columns]

In [12]:
states_df['case_day'] = states_df.groupby('state')['cases'].diff().fillna(0)
states_df

           date    state  fips  cases  deaths  case_day
0     3/13/2020  Alabama     1      6       0      0.00
1     3/14/2020  Alabama     1     12       0      6.00
2     3/15/2020  Alabama     1     23       0     11.00
3     3/16/2020  Alabama     1     29       0      6.00
4     3/17/2020  Alabama     1     39       0     10.00
...         ...      ...   ...    ...     ...       ...
5454   6/5/2020  Wyoming    56    933      17     12.00
5455   6/6/2020  Wyoming    56    939      17      6.00
5456   6/7/2020  Wyoming    56    947      17      8.00
5457   6/8/2020  Wyoming    56    960      17     13.00
5458   6/9/2020  Wyoming    56    970      17     10.00

[5459 rows x 6 columns]

In [13]:
states_df['death_day'] = states_df.groupby('state')['deaths'].diff().fillna(0)
states_df.to_csv('us-states.csv')